const seedCards = [
  {bank:'招商银行',short:'招行',mark:'blue',last:'8019',limit:50000,used:1463,due:'8月1日',status:'已还清',urgent:false},
  {bank:'中国银行',short:'中行',mark:'red',last:'6131',limit:80000,used:11427,due:'8月2日',status:'待还款',urgent:true},
  {bank:'交通银行',short:'交行',mark:'orange',last:'4905',limit:193242,used:101379,due:'8月3日',status:'待还款',urgent:true},
  {bank:'工商银行',short:'工行',mark:'red',last:'2118',limit:64500,used:16547,due:'8月5日',status:'已还清',urgent:false},
  {bank:'平安银行',short:'平安',mark:'teal',last:'6787',limit:100000,used:3049,due:'8月6日',status:'已还清',urgent:false},
  {bank:'浦发银行',short:'浦发',mark:'purple',last:'2306',limit:0,used:0,due:'8月7日',status:'未使用',urgent:false},
  {bank:'建设银行',short:'建行',mark:'blue',last:'4666',limit:120000,used:72409,due:'8月8日',status:'待还款',urgent:true},
  {bank:'广发银行',short:'广发',mark:'orange',last:'4078',limit:200000,used:59133.03,due:'8月10日',status:'已还清',urgent:false},
  {bank:'上海银行',short:'上海',mark:'teal',last:'7142',limit:120000,used:72370.70,due:'8月11日',status:'待还款',urgent:false},
  {bank:'农业银行',short:'农行',mark:'teal',last:'7280',limit:75000,used:12749,due:'8月13日',status:'已还清',urgent:false},
  {bank:'民生银行',short:'民生',mark:'purple',last:'5815',limit:50000,used:1383,due:'8月14日',status:'已还清',urgent:false},
  {bank:'兴业银行',short:'兴业',mark:'blue',last:'7752',limit:120000,used:71787,due:'8月16日',status:'待还款',urgent:false}
];
let cards = [];
const DB_NAME = 'ledger-local-db', DB_VERSION = 1, STORE = 'cards';
const money = n => `¥${Number(n || 0).toLocaleString('zh-CN',{minimumFractionDigits:Number(n)%1?2:0,maximumFractionDigits:2})}`;
const clone = value => JSON.parse(JSON.stringify(value));
function openDb() { return new Promise((resolve,reject) => { if (!('indexedDB' in window)) return reject(new Error('IndexedDB unavailable')); const r = indexedDB.open(DB_NAME,DB_VERSION); r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id',autoIncrement:true}); r.onsuccess=()=>resolve(r.result); r.onerror=()=>reject(r.error); }); }
async function loadCards() { const raw=localStorage.getItem('ledger-cards'); if(raw) { try { return JSON.parse(raw); } catch(_) {} } const initial=clone(seedCards); localStorage.setItem('ledger-cards',JSON.stringify(initial)); try { await saveAll(initial); } catch(_) {} return initial; }
async function saveAll(rows) { const clean=rows.map(row=>{const copy={...row};if(copy.id===undefined)delete copy.id;return copy}); localStorage.setItem('ledger-cards',JSON.stringify(clean)); try { const db=await openDb(); await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),store=tx.objectStore(STORE);store.clear();clean.forEach(row=>store.add(row));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);}); } catch(_) {} }
function saveCards(){return saveAll(cards)}
function totals(){const limit=cards.reduce((s,c)=>s+Number(c.limit||0),0),used=cards.reduce((s,c)=>s+Number(c.used||0),0);return{limit,used,available:Math.max(0,limit-used),percent:limit?Math.min(100,used/limit*100):0}}
function cardHtml(c){return `<button class="card-item" data-card="${c.last}"><span class="bank-mark ${c.mark}">${c.short}</span><span class="card-main"><strong class="card-name">${c.bank}</strong><span class="card-sub">信用卡 · 尾号 ${c.last}</span></span><span class="card-right"><strong class="card-amount">${money(c.used)}</strong><span class="card-due ${c.urgent?'':'ok'}">${c.due} · ${c.status}</span></span><span class="chevron">›</span></button>`}
function billHtml(c){return `<article class="bill-item"><div class="bill-top"><span class="bill-date">${c.due} · ${c.bank}</span><span class="bill-status ${c.status==='已还清'?'green':''}">${c.status}</span></div><div class="bill-bank"><span class="bank-mark ${c.mark}" style="width:26px;height:26px;border-radius:8px;font-size:9px">${c.short}</span><span>尾号 ${c.last}</span><strong class="bill-amount">${money(c.used)}</strong></div><div class="bill-bottom"><span>预计最低还款 ${money(Math.round(c.used*.1))}</span><span>账单日 · 本地记录</span></div></article>`}
function render(){const t=totals();document.querySelector('.hero-number').innerHTML=`${money(t.limit)}<span class="hero-unit">总额度</span>`;document.querySelector('.usage-track span').style.width=`${t.percent}%`;document.querySelector('.usage-meta').innerHTML=`<span>已用 ${money(t.used)}</span><strong>${t.percent.toFixed(1)}%</strong>`;document.querySelector('.summary-grid').innerHTML=`<div><span>固定额度</span><strong>${money(t.limit)}</strong></div><div><span>临时额度</span><strong>¥0</strong></div><div><span>可用额度</span><strong>${money(t.available)}</strong></div>`;const urgent=cards.filter(c=>c.urgent&&c.status!=='已还清');document.querySelector('.repayment-alert strong').textContent=`${urgent.length} 笔账单即将到期`;document.querySelector('.repayment-alert small').textContent=urgent.length?`最近还款日 · ${urgent[0].due}`:'当前没有待处理账单';document.getElementById('homeCards').innerHTML=cards.slice(0,4).map(cardHtml).join('');document.getElementById('allCards').innerHTML=cards.map(cardHtml).join('');document.getElementById('billList').innerHTML=urgent.map(billHtml).join('')||'<p class="muted">暂无待还款账单</p>';document.getElementById('cardsCount').textContent=`${cards.length} 张卡片`;document.querySelector('[data-filter="all"] span').textContent=cards.length;document.querySelector('[data-filter="urgent"] span').textContent=urgent.length;bindCards()}
const pageTitle={home:'总览',cards:'我的卡片',repayment:'还款',settings:'设置'};
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===page));document.getElementById('pageTitle').textContent=pageTitle[page];window.scrollTo({top:0,behavior:'smooth'})}
function bindCards(){document.querySelectorAll('[data-card]').forEach(el=>el.addEventListener('click',()=>openCard(el.dataset.card)))}
function showModal(){const m=document.getElementById('modalBackdrop');m.classList.add('show');m.setAttribute('aria-hidden','false')}
function closeModal(){const m=document.getElementById('modalBackdrop');m.classList.remove('show');m.setAttribute('aria-hidden','true')}
function inputForm(c={}){return `<div class="detail-grid"><label class="detail-cell"><span>发卡银行</span><input class="modal-input" data-field="bank" value="${c.bank||''}" placeholder="例如 招商银行"></label><label class="detail-cell"><span>卡号后四位</span><input class="modal-input" data-field="last" inputmode="numeric" maxlength="4" value="${c.last||''}" placeholder="8019"></label><label class="detail-cell"><span>总额度</span><input class="modal-input" data-field="limit" inputmode="decimal" value="${c.limit??''}" placeholder="50000"></label><label class="detail-cell"><span>已用额度</span><input class="modal-input" data-field="used" inputmode="decimal" value="${c.used??''}" placeholder="0"></label><label class="detail-cell"><span>还款日</span><input class="modal-input" data-field="due" value="${c.due||''}" placeholder="每月 1 日"></label><label class="detail-cell"><span>状态</span><select class="modal-input" data-field="status"><option ${c.status==='待还款'?'selected':''}>待还款</option><option ${c.status==='已还清'?'selected':''}>已还清</option><option ${c.status==='未使用'?'selected':''}>未使用</option></select></label></div>`}
function openCard(last){const c=cards.find(x=>x.last===last);if(!c)return;document.getElementById('modalTitle').textContent='卡片详情';document.getElementById('modalBody').innerHTML=`<div class="detail-hero"><span class="bank-mark ${c.mark}">${c.short}</span><div><strong>${c.bank}</strong><span>信用卡 · 尾号 ${c.last}</span></div></div><div class="detail-amount">${money(c.used)}</div><div class="detail-caption">当前已用额度</div><div class="detail-progress"><span style="width:${c.limit?Math.min(100,c.used/c.limit*100):0}%"></span></div><div class="detail-grid"><div class="detail-cell"><span>总额度</span><strong>${money(c.limit)}</strong></div><div class="detail-cell"><span>可用额度</span><strong>${money(Math.max(0,c.limit-c.used))}</strong></div></div><div class="detail-row"><span>还款日</span><strong>${c.due}</strong></div><div class="detail-row"><span>状态</span><strong>${c.status}</strong></div><button class="primary-action" data-action="edit">编辑卡片信息</button>`;document.querySelector('[data-action="edit"]').addEventListener('click',()=>openEdit(c));showModal()}
function openEdit(c){document.getElementById('modalTitle').textContent='编辑卡片信息';document.getElementById('modalBody').innerHTML=`${inputForm(c)}<button class="primary-action" data-action="save">保存修改</button><button class="secondary-action" data-action="delete">删除这张卡片</button>`;document.querySelector('[data-action="save"]').addEventListener('click',()=>saveForm(c));document.querySelector('[data-action="delete"]').addEventListener('click',async()=>{if(!confirm('确定删除这张卡片吗？'))return;cards=cards.filter(x=>x!==c);await saveCards();closeModal();render()})}
async function saveForm(existing){const get=k=>document.querySelector(`[data-field="${k}"]`).value.trim(),bank=get('bank'),last=get('last'),limit=Number(get('limit')),used=Number(get('used')),due=get('due'),status=get('status');if(!bank||!/\d{4}/.test(last)||!Number.isFinite(limit)||limit<0||!Number.isFinite(used)||used<0||!due)return alert('请填写完整且有效的卡片信息');const target=existing||{id:undefined};Object.assign(target,{bank,short:bank.slice(0,2),mark:existing?.mark||['blue','teal','orange','purple','red'][cards.length%5],last,limit,used,due,status,urgent:status==='待还款'});if(!existing)cards.unshift(target);await saveCards();closeModal();render()}
function exportData(){const blob=new Blob([JSON.stringify(cards,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`账务管家备份-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function importData(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=async()=>{try{const parsed=JSON.parse(await input.files[0].text());if(!Array.isArray(parsed))throw new Error();cards=parsed;await saveCards();render();alert('数据已恢复')}catch(_){alert('备份文件格式不正确')}};input.click()}
document.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.nav)));document.querySelector('[data-action="settings"]').addEventListener('click',()=>go('settings'));document.querySelector('[data-action="filter"]').addEventListener('click',()=>document.getElementById('filterRow').classList.toggle('show'));document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));chip.classList.add('selected');filterCards()}));document.getElementById('searchInput').addEventListener('input',filterCards);function filterCards(){const q=document.getElementById('searchInput').value.trim().toLowerCase(),active=document.querySelector('.chip.selected')?.dataset.filter||'all';let list=cards.filter(c=>!q||`${c.bank}${c.last}${c.short}`.toLowerCase().includes(q));if(active==='urgent')list=list.filter(c=>c.urgent&&c.status!=='已还清');if(active==='available')list=list.filter(c=>c.limit-c.used>0);document.getElementById('allCards').innerHTML=list.map(cardHtml).join('');document.getElementById('cardsCount').textContent=`${list.length} 张卡片`;bindCards()}
document.getElementById('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop'||e.target.closest('[data-action="close"]'))closeModal()});document.querySelector('[data-action="add"]').addEventListener('click',()=>{document.getElementById('modalTitle').textContent='添加新卡片';document.getElementById('modalBody').innerHTML=`${inputForm({status:'待还款'})}<button class="primary-action" data-action="save">保存卡片</button>`;document.querySelector('[data-action="save"]').addEventListener('click',()=>saveForm());showModal()});document.querySelector('[data-action="refresh"]').addEventListener('click',e=>{e.currentTarget.textContent='✓';setTimeout(()=>e.currentTarget.textContent='↻',1000)});document.querySelector('[data-action="export"]').addEventListener('click',exportData);document.querySelector('[data-action="import"]').addEventListener('click',importData);
loadCards().then(rows=>{cards=rows;render()}).catch(()=>{cards=clone(seedCards);render()});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));

