const seedCards = [
  {bank:'鎷涘晢閾惰',short:'鎷涜',mark:'blue',last:'8019',limit:50000,used:1463,due:'8鏈?鏃?,status:'宸茶繕娓?,urgent:false},
  {bank:'涓浗閾惰',short:'涓',mark:'red',last:'6131',limit:80000,used:11427,due:'8鏈?鏃?,status:'寰呰繕娆?,urgent:true},
  {bank:'浜ら€氶摱琛?,short:'浜よ',mark:'orange',last:'4905',limit:193242,used:101379,due:'8鏈?鏃?,status:'寰呰繕娆?,urgent:true},
  {bank:'宸ュ晢閾惰',short:'宸ヨ',mark:'red',last:'2118',limit:64500,used:16547,due:'8鏈?鏃?,status:'宸茶繕娓?,urgent:false},
  {bank:'骞冲畨閾惰',short:'骞冲畨',mark:'teal',last:'6787',limit:100000,used:3049,due:'8鏈?鏃?,status:'宸茶繕娓?,urgent:false},
  {bank:'娴﹀彂閾惰',short:'娴﹀彂',mark:'purple',last:'2306',limit:0,used:0,due:'8鏈?鏃?,status:'鏈娇鐢?,urgent:false},
  {bank:'寤鸿閾惰',short:'寤鸿',mark:'blue',last:'4666',limit:120000,used:72409,due:'8鏈?鏃?,status:'寰呰繕娆?,urgent:true},
  {bank:'骞垮彂閾惰',short:'骞垮彂',mark:'orange',last:'4078',limit:200000,used:59133.03,due:'8鏈?0鏃?,status:'宸茶繕娓?,urgent:false},
  {bank:'涓婃捣閾惰',short:'涓婃捣',mark:'teal',last:'7142',limit:120000,used:72370.70,due:'8鏈?1鏃?,status:'寰呰繕娆?,urgent:false},
  {bank:'鍐滀笟閾惰',short:'鍐滆',mark:'teal',last:'7280',limit:75000,used:12749,due:'8鏈?3鏃?,status:'宸茶繕娓?,urgent:false},
  {bank:'姘戠敓閾惰',short:'姘戠敓',mark:'purple',last:'5815',limit:50000,used:1383,due:'8鏈?4鏃?,status:'宸茶繕娓?,urgent:false},
  {bank:'鍏翠笟閾惰',short:'鍏翠笟',mark:'blue',last:'7752',limit:120000,used:71787,due:'8鏈?6鏃?,status:'寰呰繕娆?,urgent:false}
];
let cards = [];
const DB_NAME = 'ledger-local-db', DB_VERSION = 1, STORE = 'cards';
const money = n => `楼${Number(n || 0).toLocaleString('zh-CN',{minimumFractionDigits:Number(n)%1?2:0,maximumFractionDigits:2})}`;
const clone = value => JSON.parse(JSON.stringify(value));
function openDb() { return new Promise((resolve,reject) => { if (!('indexedDB' in window)) return reject(new Error('IndexedDB unavailable')); const r = indexedDB.open(DB_NAME,DB_VERSION); r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id',autoIncrement:true}); r.onsuccess=()=>resolve(r.result); r.onerror=()=>reject(r.error); }); }
async function loadCards() { const raw=localStorage.getItem('ledger-cards'); if(raw) { try { return JSON.parse(raw); } catch(_) {} } const initial=clone(seedCards); localStorage.setItem('ledger-cards',JSON.stringify(initial)); try { await saveAll(initial); } catch(_) {} return initial; }
async function saveAll(rows) { const clean=rows.map(row=>{const copy={...row};if(copy.id===undefined)delete copy.id;return copy}); localStorage.setItem('ledger-cards',JSON.stringify(clean)); try { const db=await openDb(); await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),store=tx.objectStore(STORE);store.clear();clean.forEach(row=>store.add(row));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);}); } catch(_) {} }
function saveCards(){return saveAll(cards)}
function totals(){const limit=cards.reduce((s,c)=>s+Number(c.limit||0),0),used=cards.reduce((s,c)=>s+Number(c.used||0),0);return{limit,used,available:Math.max(0,limit-used),percent:limit?Math.min(100,used/limit*100):0}}
function cardHtml(c){return `<button class="card-item" data-card="${c.last}"><span class="bank-mark ${c.mark}">${c.short}</span><span class="card-main"><strong class="card-name">${c.bank}</strong><span class="card-sub">淇＄敤鍗?路 灏惧彿 ${c.last}</span></span><span class="card-right"><strong class="card-amount">${money(c.used)}</strong><span class="card-due ${c.urgent?'':'ok'}">${c.due} 路 ${c.status}</span></span><span class="chevron">鈥?/span></button>`}
function billHtml(c){return `<article class="bill-item"><div class="bill-top"><span class="bill-date">${c.due} 路 ${c.bank}</span><span class="bill-status ${c.status==='宸茶繕娓??'green':''}">${c.status}</span></div><div class="bill-bank"><span class="bank-mark ${c.mark}" style="width:26px;height:26px;border-radius:8px;font-size:9px">${c.short}</span><span>灏惧彿 ${c.last}</span><strong class="bill-amount">${money(c.used)}</strong></div><div class="bill-bottom"><span>棰勮鏈€浣庤繕娆?${money(Math.round(c.used*.1))}</span><span>璐﹀崟鏃?路 鏈湴璁板綍</span></div></article>`}
function render(){const t=totals();document.querySelector('.hero-number').innerHTML=`${money(t.limit)}<span class="hero-unit">鎬婚搴?/span>`;document.querySelector('.usage-track span').style.width=`${t.percent}%`;document.querySelector('.usage-meta').innerHTML=`<span>宸茬敤 ${money(t.used)}</span><strong>${t.percent.toFixed(1)}%</strong>`;document.querySelector('.summary-grid').innerHTML=`<div><span>鍥哄畾棰濆害</span><strong>${money(t.limit)}</strong></div><div><span>涓存椂棰濆害</span><strong>楼0</strong></div><div><span>鍙敤棰濆害</span><strong>${money(t.available)}</strong></div>`;const urgent=cards.filter(c=>c.urgent&&c.status!=='宸茶繕娓?);document.querySelector('.repayment-alert strong').textContent=`${urgent.length} 绗旇处鍗曞嵆灏嗗埌鏈焋;document.querySelector('.repayment-alert small').textContent=urgent.length?`鏈€杩戣繕娆炬棩 路 ${urgent[0].due}`:'褰撳墠娌℃湁寰呭鐞嗚处鍗?;document.getElementById('homeCards').innerHTML=cards.slice(0,4).map(cardHtml).join('');document.getElementById('allCards').innerHTML=cards.map(cardHtml).join('');document.getElementById('billList').innerHTML=urgent.map(billHtml).join('')||'<p class="muted">鏆傛棤寰呰繕娆捐处鍗?/p>';document.getElementById('cardsCount').textContent=`${cards.length} 寮犲崱鐗嘸;document.querySelector('[data-filter="all"] span').textContent=cards.length;document.querySelector('[data-filter="urgent"] span').textContent=urgent.length;bindCards()}
const pageTitle={home:'鎬昏',cards:'鎴戠殑鍗＄墖',repayment:'杩樻',settings:'璁剧疆'};
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===page));document.getElementById('pageTitle').textContent=pageTitle[page];window.scrollTo({top:0,behavior:'smooth'})}
function bindCards(){document.querySelectorAll('[data-card]').forEach(el=>el.addEventListener('click',()=>openCard(el.dataset.card)))}
function showModal(){const m=document.getElementById('modalBackdrop');m.classList.add('show');m.setAttribute('aria-hidden','false')}
function closeModal(){const m=document.getElementById('modalBackdrop');m.classList.remove('show');m.setAttribute('aria-hidden','true')}
function inputForm(c={}){return `<div class="detail-grid"><label class="detail-cell"><span>鍙戝崱閾惰</span><input class="modal-input" data-field="bank" value="${c.bank||''}" placeholder="渚嬪 鎷涘晢閾惰"></label><label class="detail-cell"><span>鍗″彿鍚庡洓浣?/span><input class="modal-input" data-field="last" inputmode="numeric" maxlength="4" value="${c.last||''}" placeholder="8019"></label><label class="detail-cell"><span>鎬婚搴?/span><input class="modal-input" data-field="limit" inputmode="decimal" value="${c.limit??''}" placeholder="50000"></label><label class="detail-cell"><span>宸茬敤棰濆害</span><input class="modal-input" data-field="used" inputmode="decimal" value="${c.used??''}" placeholder="0"></label><label class="detail-cell"><span>杩樻鏃?/span><input class="modal-input" data-field="due" value="${c.due||''}" placeholder="姣忔湀 1 鏃?></label><label class="detail-cell"><span>鐘舵€?/span><select class="modal-input" data-field="status"><option ${c.status==='寰呰繕娆??'selected':''}>寰呰繕娆?/option><option ${c.status==='宸茶繕娓??'selected':''}>宸茶繕娓?/option><option ${c.status==='鏈娇鐢??'selected':''}>鏈娇鐢?/option></select></label></div>`}
function openCard(last){const c=cards.find(x=>x.last===last);if(!c)return;document.getElementById('modalTitle').textContent='鍗＄墖璇︽儏';document.getElementById('modalBody').innerHTML=`<div class="detail-hero"><span class="bank-mark ${c.mark}">${c.short}</span><div><strong>${c.bank}</strong><span>淇＄敤鍗?路 灏惧彿 ${c.last}</span></div></div><div class="detail-amount">${money(c.used)}</div><div class="detail-caption">褰撳墠宸茬敤棰濆害</div><div class="detail-progress"><span style="width:${c.limit?Math.min(100,c.used/c.limit*100):0}%"></span></div><div class="detail-grid"><div class="detail-cell"><span>鎬婚搴?/span><strong>${money(c.limit)}</strong></div><div class="detail-cell"><span>鍙敤棰濆害</span><strong>${money(Math.max(0,c.limit-c.used))}</strong></div></div><div class="detail-row"><span>杩樻鏃?/span><strong>${c.due}</strong></div><div class="detail-row"><span>鐘舵€?/span><strong>${c.status}</strong></div><button class="primary-action" data-action="edit">缂栬緫鍗＄墖淇℃伅</button>`;document.querySelector('[data-action="edit"]').addEventListener('click',()=>openEdit(c));showModal()}
function openEdit(c){document.getElementById('modalTitle').textContent='缂栬緫鍗＄墖淇℃伅';document.getElementById('modalBody').innerHTML=`${inputForm(c)}<button class="primary-action" data-action="save">淇濆瓨淇敼</button><button class="secondary-action" data-action="delete">鍒犻櫎杩欏紶鍗＄墖</button>`;document.querySelector('[data-action="save"]').addEventListener('click',()=>saveForm(c));document.querySelector('[data-action="delete"]').addEventListener('click',async()=>{if(!confirm('纭畾鍒犻櫎杩欏紶鍗＄墖鍚楋紵'))return;cards=cards.filter(x=>x!==c);await saveCards();closeModal();render()})}
async function saveForm(existing){const get=k=>document.querySelector(`[data-field="${k}"]`).value.trim(),bank=get('bank'),last=get('last'),limit=Number(get('limit')),used=Number(get('used')),due=get('due'),status=get('status');if(!bank||!/\d{4}/.test(last)||!Number.isFinite(limit)||limit<0||!Number.isFinite(used)||used<0||!due)return alert('璇峰～鍐欏畬鏁翠笖鏈夋晥鐨勫崱鐗囦俊鎭?);const target=existing||{id:undefined};Object.assign(target,{bank,short:bank.slice(0,2),mark:existing?.mark||['blue','teal','orange','purple','red'][cards.length%5],last,limit,used,due,status,urgent:status==='寰呰繕娆?});if(!existing)cards.unshift(target);await saveCards();closeModal();render()}
function exportData(){const blob=new Blob([JSON.stringify(cards,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`璐﹀姟绠″澶囦唤-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
function importData(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=async()=>{try{const parsed=JSON.parse(await input.files[0].text());if(!Array.isArray(parsed))throw new Error();cards=parsed;await saveCards();render();alert('鏁版嵁宸叉仮澶?)}catch(_){alert('澶囦唤鏂囦欢鏍煎紡涓嶆纭?)}};input.click()}
document.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.nav)));document.querySelector('[data-action="settings"]').addEventListener('click',()=>go('settings'));document.querySelector('[data-action="filter"]').addEventListener('click',()=>document.getElementById('filterRow').classList.toggle('show'));document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));chip.classList.add('selected');filterCards()}));document.getElementById('searchInput').addEventListener('input',filterCards);function filterCards(){const q=document.getElementById('searchInput').value.trim().toLowerCase(),active=document.querySelector('.chip.selected')?.dataset.filter||'all';let list=cards.filter(c=>!q||`${c.bank}${c.last}${c.short}`.toLowerCase().includes(q));if(active==='urgent')list=list.filter(c=>c.urgent&&c.status!=='宸茶繕娓?);if(active==='available')list=list.filter(c=>c.limit-c.used>0);document.getElementById('allCards').innerHTML=list.map(cardHtml).join('');document.getElementById('cardsCount').textContent=`${list.length} 寮犲崱鐗嘸;bindCards()}
document.getElementById('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop'||e.target.closest('[data-action="close"]'))closeModal()});document.querySelector('[data-action="add"]').addEventListener('click',()=>{document.getElementById('modalTitle').textContent='娣诲姞鏂板崱鐗?;document.getElementById('modalBody').innerHTML=`${inputForm({status:'寰呰繕娆?})}<button class="primary-action" data-action="save">淇濆瓨鍗＄墖</button>`;document.querySelector('[data-action="save"]').addEventListener('click',()=>saveForm());showModal()});document.querySelector('[data-action="refresh"]').addEventListener('click',e=>{e.currentTarget.textContent='鉁?;setTimeout(()=>e.currentTarget.textContent='鈫?,1000)});document.querySelector('[data-action="export"]').addEventListener('click',exportData);document.querySelector('[data-action="import"]').addEventListener('click',importData);
loadCards().then(rows=>{cards=rows;render()}).catch(()=>{cards=clone(seedCards);render()});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));

